services:
  - type: web
    name: nodered-secure
    env: docker
    plan: starter
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
